# Installing TensorFlow

In [13]:
from django.db.models.expressions import result

pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


**I accidentally skipped the introduction, so I was confused about TensorFlow for a long time. I thought machine learning was just too hard for me—a newbie who couldn’t understand a word. I even went through the TensorFlow documentation, but it didn’t help much at first.
Eventually, I realised that I had skipped the entire introductory part and jumped straight into the practice section. No wonder it didn’t make sense! Now that I’ve figured that out, I’m going back to learn the algorithms properly. - -!**

In [14]:
pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "/opt/anaconda3/lib/python3.12/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/lib/python3.12/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/anaconda3/lib/python3.12/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokeniz

# Importing TensorFlow

In [15]:
import tensorflow as tf
print(tf.__version__) # make sure the version is 2.x

2.19.0


# Tensors
**"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." (https://www.tensorflow.org/guide/tensor)**
### Each tensor has a data type and a shape.
### Data Types include: float32, int32, string and others.
### Shape: Represents the dimension of data.

# Creating Tensors

In [16]:
string = tf.Variable('Hello, TensorFlow!', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

# Rank/Degree of Tensors


In [17]:
# rank means the number of dimensions
rank1_tensor = tf.Variable(["Test"], tf.string) # one tensor
rank2_tensor = tf.Variable([["Test", "ok"], ["test", "yes"]],tf.string) # two tensor, a list inside--> matrices

In [18]:
# call the method to determine the rank of a tensor
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

 # Shape of Tensors

In [19]:
rank2_tensor.shape

TensorShape([2, 2])

# Changing Shape

In [20]:
tensor1 = tf.ones([1,2,3]) # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1,[2,3,1]) # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2,[3,-1]) # -1 tells the tensor to calculate the size of the dimension in that place. this will reshape the tensor to [3,2]
# the number of elements in the reshaped tensor must match the number in the original

In [21]:
# have a look at our different tensors
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Slicing Tensors

**Ex: tensor[dim1, dim2, dim3]**

**Using comma seperated values inside the set of square brackets.**

In [30]:
# Create a 2D tensor
matrix = [[1,2,3,4,5],[6,7,8,9,10],
          [11,12,13,14,15],[16,17,18,19,20]]
tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [31]:
# Now let's select some different rows and columns from our tensor

three = tensor[0,2] # select the 3rd element from the 1st row
print(three)

row1 = tensor[0] # select the first row
print(row1)

column1 = tensor[:,0] # select the first column
print(column1)

row2_and_4 = tensor[1::2] # select second and fourth row
print(row2_and_4)

column1_in_row_2_and_3 = tensor[1:3,0]
print(column1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


# Types of Tensors
### Variable 
### Constant - immutable
### Placeholder - immutable
### SparseTensor - immutable